# tasks file for copykey
- name: "write pub key to file"
  copy: 
    src: /home/jenkins/.ssh/id_rsa.pub
    desc: /home/TasnimBegum/key.pub

- name: "write key to file"
  copy: 
    src: /home/jenkins/.ssh/id_rsa
    dest: /home/TasnimBegum/key